# Default evaluation arguments for eval.py
# Dataset
data_path: data/hymenoptera_data/val
batch_size: 16
num_workers: 0

# Checkpoint
checkpoint: "experiments/checkpoints/exp-20250823-020050/best_model.pth"
# Device
use_gpu: true
